[SASS-466] Removed sensitive user data from URL
hmrc/income-tax-submission pull request #18
Opened 2021-03-17 18:40 UTC by abiodxn

2021-03-19 12:31 UTC, Dula-J commented on app/controllers/predicates/AuthorisedAction.scala
> +    request.headers.get("mtditid").fold {
Could you add the following to the  line 284 of AuthorisedActionSpec

`
        "the request does not contain mtditid header" in {
          object AuthException extends AuthorisationException("Some reason")

          lazy val result = {
            auth.async(block)
          }

          status(result(FakeRequest())) mustBe UNAUTHORIZED
        }
`

2021-03-19 12:33 UTC, Dula-J commented on it/api/GetIncomeSourcesITest.scala
> +          url = s"/income-tax-dividends/income-tax/nino/AA123123A/sources\\?taxYear=2019&mtditid=123123123",
For a number of these error scenario tests i don't think we need all the stubs so we can remove them, and if we do need any, we can remove the mtditid from the url

2021-03-19 12:34 UTC, Dula-J commented on it/api/GetIncomeSourcesITest.scala
> +          url = s"/income-tax-dividends/income-tax/nino/AA123123A/sources\\?taxYear=2019&mtditid=123123123",
These stubs can be removed because this request would fail fast in the AuthorisedAction so the stubs would never be called.

2021-03-19 12:36 UTC, Dula-J commented on test/services/GetIncomeSourcesServiceSpec.scala
> +          .expects("12345678", 1234, *)
To align with the implementation of the other services and make this more robust we should remove the wildcard `*` from the expects and specify a headerCarrier that contains the extra mtditid header

2021-03-19 12:36 UTC, Dula-J requested changes
See comments

2021-03-19 13:57 UTC, BenCosfordHMRC commented
theres conflicts now

2021-03-19 16:54 UTC, BenCosfordHMRC approved these changes

2021-03-22 11:02 UTC, Dula-J approved these changes

2021-03-22 14:03 UTC, merged