SASS-79
hmrc/income-tax-submission pull request #3
Opened 2020-10-27 23:46 UTC by TheDeadlyPianist

2020-10-28 14:43 UTC, juamalBlackman commented
Submitted Dividends connector missing wild card test case
<img width="1051" alt="Screenshot 2020-10-28 at 2 36 17 pm" src="https://user-images.githubusercontent.com/63247344/97451656-de5f2e80-192b-11eb-8ae3-a8c38dce2362.png">

2020-10-28 14:52 UTC, juamalBlackman commented on app/connectors/httpParsers/SubmittedDividendsParser.scala
> +        case SERVICE_UNAVAILABLE => Left(ServiceUnavailableError)
is this case actually needed?

2020-10-28 15:01 UTC, juamalBlackman commented on app/models/ErrorResponse.scala
> +  500, "INTERNAL_SERVER_ERROR", "A downstream service didn't response as expected"
maybe use http status import instead of magic number

2020-10-28 15:04 UTC, juamalBlackman commented on app/models/ErrorResponse.scala
> +  500, "INTERNAL_SERVER_ERROR", "A downstream service didn't response as expected"
typo change response to respond

2020-10-28 16:02 UTC, juamalBlackman requested changes
<img width="1788" alt="Screenshot 2020-10-28 at 3 58 53 pm" src="https://user-images.githubusercontent.com/63247344/97462528-bc1ede00-1936-11eb-9ed4-1bb9a89469a6.png">
Im not seeing all the right stuff in coverage unsure if this is due to my settings or something else that needs to be included in the project. If it is the latter would be great if you could show me how to set this up

2020-10-29 10:15 UTC, TheDeadlyPianist commented on app/models/IncomeSourcesResponseModel.scala
> +}
Heads up, new lines at the end of the file are a stylistic choice. Not something you can ask for in a review.
I always add them, but I'm unsure if James does.

2020-10-29 10:16 UTC, TheDeadlyPianist commented on conf/app.routes
> +GET        /income-tax/nino/:nino/sources     controllers.GetIncomeSourcesController.getIncomeSources(nino: String, taxYear: Int, mtditid: String)
Not necessary

2020-10-29 10:20 UTC, TheDeadlyPianist commented on app/models/SubmittedDividendsModel.scala
> +}
I assume James did it for separation of concerns, so I'm going to leave it.

2020-10-29 13:39 UTC, merged